### ISSUE TITLE
Doubt the authenticity of your code

### ISSUE THREAD

**Issue by LIUJAING** [mxt0607/FTL_SOH-estimation#1]
In the final test part, the model is imported separately, and the PSO parameters are also。

**Comment by CayuLon** [comment]
> In the final test part, the model is imported separately, and the PSO parameters are also。

The model and hyperparameters you are talking about should be trained by the author for 6000 times, so that you can use them without training.You can comment these out and try again

**Comment by mxt0607** [comment]
> In the final test part, the model is imported separately, and the PSO parameters are also。

You can also train the model from scratch, and save the final model as well as the hyperparameters. For ease of testing and alleviating the discrepancy of GPU, the trained model and hyperparameters have also been saved, which you can easily load and test.

**Comment by CayuLon** [comment]
> The model and hyperparameters you are talking about should be trained by the author for 6000 times, so that you can use them without training.You can comment these out and try again

May I ask why the test is a straight line?

**Comment by CayuLon** [comment]
> > In the final test part, the model is imported separately, and the PSO parameters are also。
> 
> You can also train the model from scratch, and save the final model as well as the hyperparameters. For ease of testing and alleviating the discrepancy of GPU, the trained model and hyperparameters have also been saved, which you can easily load and test.

May I ask why the test is a straight line?

**Comment by mxt0607** [comment]
> > > In the final test part, the model is imported separately, and the PSO parameters are also。
> > 
> > 
> > You can also train the model from scratch, and save the final model as well as the hyperparameters. For ease of testing and alleviating the discrepancy of GPU, the trained model and hyperparameters have also been saved, which you can easily load and test.
> 
> May I ask why the test is a straight line?

The State of Health (SOH) for battery A2 exhibits a linear degradation pattern, in contrast to the other batteries in our study, which generally display various SOH degradation trends.
